### PR TITLE
research on usdc cross chain on trustless work

### PR DESCRIPTION
**Pull request by KoxyG**

### CODE REVIEW

**Comment by KoxyG** [comment]
Reference to issue https://github.com/Tico4Chain-Coders/Product/issues/5

**Review by techrebelgit — APPROVED** [review]
Thank you. I think Circle CCTP still does not support Stellar, but I know they plan to soon. 
I had researched AllBridge before, but having all of these fragmented USDCx seems like adding complexity. 
I would like your comments on that

**Comment by KoxyG** [comment]
> Thank you. I think Circle CCTP still does not support Stellar, but I know they plan to soon. I had researched AllBridge before, but having all of these fragmented USDCx seems like adding complexity. I would like your comments on that

no it doesn't add complexities. This works for only address to address on stellar. I have been discussing with the Allbridge team on the ability to send from a contract to a soroban contract, instead of sending straight up to the wallet address, but this is what they have to say.
Screenshot 2024-12-27 at 6 42 50 AM



For circle, i think its still under development. I saw it is yet to be listed as a supported blockchain, but i think they are currently working on it.
I saw this 
https://developers.circle.com/circle-mint/blockchain-confirmations#confirmations

https://developers.circle.com/circle-mint/blockchain-confirmations#confirmations

**Comment by KoxyG** [comment]
My research doesn't stop here for this is a knowledge i myself i am very interested in. There might be protocols or infrastructures being developed or still under development on this use case. 

But i will suggest, Trustless work creates its own solution to this, or wait a little bit and keep researching for a soluton might be out there or probably might  still be on its way. @techrebelgit

**Comment by techrebelgit** [comment]
> no it doesn't add complexities. This works for only address to address on stellar. I have been discussing with the Allbridge team on the ability to send from a contract to a soroban contract, instead of sending straight up to the wallet address

Understood, but what I meant is that then the other party of the escrow would be receiving USDCab or whatever, not "clean" USDC. This would require that party to de-bridge from USDCab to USDC somehow to be able to offramp. Am I right on this?

> But i will suggest, Trustless work creates its own solution to this, or wait a little bit and keep researching for a soluton might be out there or probably might still be on its way.

From what I see CCTP would be amazing for this. Because it provides "clean" USDC at the other end of the bridge. So waiting makes sense. 


The other possibility would be for TW to build this using a centralized exchange. Like connecting to Coinbase and just deposit USDC on Base and withdraw USDC on Stellar. But that requires liquidity from our end.

**Comment by KoxyG** [comment]
> > no it doesn't add complexities. This works for only address to address on stellar. I have been discussing with the Allbridge team on the ability to send from a contract to a soroban contract, instead of sending straight up to the wallet address
> 
> Understood, but what I meant is that then the other party of the escrow would be receiving USDCab or whatever, not "clean" USDC. This would require that party to de-bridge from USDCab to USDC somehow to be able to offramp. Am I right on this?
> 
> > But i will suggest, Trustless work creates its own solution to this, or wait a little bit and keep researching for a soluton might be out there or probably might still be on its way.
> 
> From what I see CCTP would be amazing for this. Because it provides "clean" USDC at the other end of the bridge. So waiting makes sense.
> 
> The other possibility would be for TW to build this using a centralized exchange. Like connecting to Coinbase and just deposit USDC on Base and withdraw USDC on Stellar. But that requires liquidity from our end.


Yes, you are correct on this one. I did a bit more research and found out that you are right once more. Currently, there isn't a direct way to get USDC from other chains onto Stellar through CCTP (Cross-Chain Transfer Protocol). While CCTP is a promising solution, it has not yet been fully implemented on Stellar.

The alternative option would be to consider using centralized solutions in the meantime  for TW to build its own solution. I know of a founder from [Bingtellar](https://bingtellar.com/), who worked on this and handles the liquidity from his end.

**Comment by KoxyG** [comment]
I know Binance is also an [anchor](https://anchors.stellar.org/?s=bina) on stellar. Maybe you check this out and see if it makes sense in anyway.

[sep-006.md](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md)
[sep-0031.md](https://github.com/stellar/stellar-protocol/tree/master/ecosystem/sep-0031.md)
[sep-0025.md](https://github.com/stellar/stellar-protocol/tree/master/ecosystem/sep-0025.md)

**Pull request merged**
